name: Build and Run Maven Project (Java 21)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Java Program
        run: java -cp target/hello-maven-1.0-SNAPSHOT.jar com.example.Hello
